name: PR assignment

on:
  pull_request:
    types:
    - opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign pull request
      uses: pozil/auto-assign-issue@v1
      with:
        assignees: ${{secrets.DEFAULT_PR_ASSIGNEE || secrets.DEFAULT_ISSUE_ASSIGNEE || 'remal'}}
