name: Bump repository activity

on:
  schedule:
  - cron: '43 2 * * *' # sync-with-template: adjust
  push:
    branches:
    - main
    paths:
    - '.github/workflows/bump-repository-activity.yml'
  workflow_dispatch: { }

jobs:
  bump-repository-activity:
    name: Bump repository activity
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: bump-repository-activity
    steps:
    - name: Get rate limits
      uses: remal-github-actions/get-rate-limits@v1
      id: getRateLimits
    - name: Bump repository activity
      if: ${{steps.getRateLimits.outputs.coreUsage < 50}}
      uses: remal-github-actions/bump-repository-activity@v1
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{env.PUSH_BACK_TOKEN}}
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        bumperFile: 'repository-activity.bumper'
        commitMessage: '[push-back] Bump repository activity'
