name: Bump repository activity

on:
  schedule:
  - cron: '0 2 * * *'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/bump-repository-activity.yml'
  workflow_dispatch: { }

env:
  PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}

jobs:
  bump-repository-activity:
    if: ${{env.PUSH_BACK_TOKEN}}
    name: Bump repository activity
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: bump-repository-activity
    steps:
    - name: Bump repository activity
      uses: remal-github-actions/bump-repository-activity@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        bumperFile: 'repository-activity.bumper'
        commitMessage: '[push-back] Bump repository activity'
