name: Bump repository activity

on:
  schedule:
  - cron: '43 2 * * *' # sync-with-template: adjust
  push:
    branches:
    - main
    paths:
    - '.github/workflows/bump-repository-activity.yml'
  workflow_dispatch: { }

env:
  PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}

jobs:
  rate-limits:
    if: ${{env.PUSH_BACK_TOKEN}}
    name: Check rate limits
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: bump-repository-activity
    steps:
    - name: Get rate limits
      uses: remal-github-actions/get-rate-limits@v1
      id: getRateLimits
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
    outputs:
      enough: ${{steps.getRateLimits.outputs.coreUsage < 50}}

  bump-repository-activity:
    needs:
    - rate-limits
    if: ${{env.PUSH_BACK_TOKEN && (github.event_name == 'push' || fromJSON(needs.rate-limits.outputs.enough) == true)}}
    name: Bump repository activity
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: bump-repository-activity
    steps:
    - name: Bump repository activity
      if: ${{github.event_name == 'push' || steps.getRateLimits.outputs.coreUsage < 50}}
      uses: remal-github-actions/bump-repository-activity@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        bumperFile: 'repository-activity.bumper'
        commitMessage: '[push-back] Bump repository activity'
