name: Check action secrets

on:
  push:
    paths:
    - '.github/workflows/*.yml'
    branches:
    - 'main'
    - 'master'
  schedule:
  - cron: '23 1 * * *' # sync-with-template: adjust
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

jobs:
  check-action-secrets:
    name: Check action secrets
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: check-action-secrets
    steps:
    - name: Get rate limits
      uses: remal-github-actions/get-rate-limits@v1
      id: getRateLimits
      with:
        githubToken: ${{secrets.LIST_SECRETS}}
    - name: Check action secrets
      if: ${{github.event_name == 'push' || steps.getRateLimits.outputs.coreUsage < 50}}
      uses: remal-github-actions/check-action-secrets@v1
      with:
        githubToken: ${{secrets.LIST_SECRETS}}
