name: Check action secrets

on:
  push:
    paths:
    - '.github/workflows/*.yml'
    branches:
    - 'main'
    - 'master'
  schedule:
  - cron: '23 1 * * *' # sync-with-template: adjust
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

jobs:
  rate-limits:
    name: Check rate limits
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: bump-repository-activity
    steps:
    - name: Get rate limits
      uses: remal-github-actions/get-rate-limits@v1
      id: getRateLimits
      with:
        githubToken: ${{secrets.LIST_SECRETS || github.token}}
    outputs:
      enough: ${{steps.getRateLimits.outputs.coreUsage < 50}}

  not-enough-rate-limits:
    needs:
    - rate-limits
    if: ${{fromJSON(needs.rate-limits.outputs.enough) != true}}
    name: Not enough rate limits
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - run: |
        echo "::warning::Not enough rate limits!"


  check-action-secrets:
    needs:
    - rate-limits
    if: ${{github.event_name == 'push' || fromJSON(needs.rate-limits.outputs.enough) == true}}
    name: Check action secrets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: check-action-secrets
    steps:
    - name: Check action secrets
      uses: remal-github-actions/check-action-secrets@v1
      with:
        githubToken: ${{secrets.LIST_SECRETS}}
