name: 'Codeowners validation'

on:
  push:
    paths:
    - '.github/CODEOWNERS'
    - '.github/workflows/codeowners-validator.yml'
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  - cron: '37 4 * * *'
  workflow_dispatch: { }

jobs:
  'Codeowners validation':
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CODEOWNERS validation
      uses: mszostok/codeowners-validator@v0.6.0
      with:
        github_access_token: '${{ github.token }}'
