name: 'Codeowners validation'

on:
  push:
    paths:
    - '.github/CODEOWNERS'
    - '.github/workflows/codeowners-validator.yml'
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  - cron: '37 4 * * *'
  workflow_dispatch: { }

jobs:
  codeowners-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Get repository owner type
      run: |
        REPO_JSON=$(curl "${{ github.api_url}}/repos/${{ github.repository	}}" -H "Authorization: token ${{ github.token }}")
        OWNER_TYPE=$(echo $REPO_JSON | jq -r '.owner.type')
        OWNER_TYPE=$(echo "$OWNER_TYPE" | tr '[:upper:]' '[:lower:]')
        echo "OWNER_TYPE=$OWNER_TYPE"

    - name: Basic CODEOWNERS validation
      uses: mszostok/codeowners-validator@v0.6.0
      with:
        checks: 'syntax,duppatterns,files'
        github_access_token: '${{ github.token }}'
